version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn
      - run: yarn test

workflows:
  version: 2
  test:
    jobs:
      - test
